spring:
  application:
    name: Conference-Booking-Service
  datasource:
    url: jdbc:h2:file:/Users/mostafad/test
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
    datasource:
      url: jdbc:h2:file:/Users/mostafad/test
      driverClassName: org.h2.Driver
      username: sa
      password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8081
  servlet:
    session:
      timeout: 30m
      cookie:
        name: USER_SESSION
        path: /
    context-path: /
logging:
  level:
    org.springframework: INFO

app:
  maintenance:
    timings:
      - start: "09:00:00"
        end: "09:15:00"
      - start: "13:00:00"
        end: "13:15:00"
      - start: "17:00:00"
        end: "17:15:00"
  conference:
    rooms:
      - name: "Amaze"
        capacity: 3
      - name: "Beauty"
        capacity: 7
      - name: "Inspire"
        capacity: 12
      - name: "Strive"
        capacity: 20